# This file includes some metadata about pages in a fictional web site
index:
  name:  Home
  title: Home Page

about:
  name:  About Us
  title: Further Information About Us

# The scheme defines how the data should be merged with files in the pages/*
# sub-directory

schema:
  tree_type: uri
  uri_paths: relative
